version: '3'
services:
   
  spring-boot-app:
    image: spring-boot-app
    build:
      context: ./baackend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dispensary
      SPRING_DATASOURCE_USERNAME: faied
      SPRING_DATASOURCE_PASSWORD: faied

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: faied
      MYSQL_PASSWORD: faied
      MYSQL_DATABASE: dispensary
    ports:
      - "3306:3306"

  react-app:
    image: react-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    


